# Defines which parameters can be displayed as part of the customisable parameter
# widgets in the centre of the dash, along with their units (default, imperial, metric),
# any conversion factors needed to convert between them, and a user friendly name to display
# in the widget.

# Users can customise this and add their own configuration with custom units and
# conversion factors if they wish instead of being limited to default, metric or imperial.
# For example, to add a configuration called 'Custom' to the speed parameter that uses knots:

#  speed:
#    label: Speed
#    units:
#      default: mps
#      imperial: mph
#      metric: kph
#      Custom: kt
#    factor:
#      imperial: 2.24
#      metric: 3.6
#      Custom: 1.944

# Note that users will also need to add this configuration to the Dashboard Config file
# under 'unitOptions' to be able to select it in the settings.
# Any parameter that doesn't have a 'Custom' unit will fall back to the default.

is_race_on:
  label: Is Race On

timestamp_ms:
  label: Timestamp
  units:
    default: ms

engine_max_rpm:
  label: Max RPM
  units:
    default: rpm

engine_idle_rpm:
  label: Idle RPM
  units:
    default: rpm

current_engine_rpm:
  label: RPM
  units:
    default: rpm

acceleration_x:
  label: X Accel

acceleration_y:
  label: Y Accel

acceleration_z:
  label: Z Accel

velocity_x:
  label: X Vel

velocity_y:
  label: Y Vel

velocity_z:
  label: Z Vel

angular_velocity_x:
  label: X Ang Vel

angular_velocity_y:
  label: Y Ang Vel

angular_velocity_z:
  label: Z Ang Vel

yaw:
  label: Yaw

pitch:
  label: Pitch

roll:
  label: Roll

norm_suspension_travel_FL:
  label: FL Sus

norm_suspension_travel_FR:
  label: FR Sus

norm_suspension_travel_RL:
  label: RL Sus

norm_suspension_travel_RR:
  label: RR Sus

tire_slip_ratio_FL:
  label: FL Slip r

tire_slip_ratio_FR:
  label: FR Slip r

tire_slip_ratio_RL:
  label: RL Slip r

tire_slip_ratio_RR:
  label: RR Slip r

wheel_rotation_speed_FL:
  label: FL Speed
  units:
    default: rps

wheel_rotation_speed_FR:
  label: FR Speed
  units:
    default: rps

wheel_rotation_speed_RL:
  label: RL Speed
  units:
    default: rps

wheel_rotation_speed_RR:
  label: RR Speed
  units:
    default: rps

wheel_on_rumble_strip_FL:
  label: FL Rumble

wheel_on_rumble_strip_FR:
  label: FR Rumble

wheel_on_rumble_strip_RL:
  label: RL Rumble

wheel_on_rumble_strip_RR:
  label: RR Rumble

wheel_in_puddle_FL:
  label: FL Puddle

wheel_in_puddle_FR:
  label: FR Puddle

wheel_in_puddle_RL:
  label: RL Puddle

wheel_in_puddle_RR:
  label: RR Puddle

surface_rumble_FL:
  label: FL Surf Rum

surface_rumble_FR:
  label: FR Surf Rum

surface_rumble_RL:
  label: RL Surf Rum

surface_rumble_RR:
  label: RR Surf Rum

tire_slip_angle_FL:
  label: FL Slip Ang

tire_slip_angle_FR:
  label: FR Slip Ang

tire_slip_angle_Rl:
  label: RL Slip Ang

tire_slip_angle_RR:
  label: RR Slip Ang

tire_combined_slip_FL:
  label: FL Com Slip

tire_combined_slip_FR:
  label: FR Com Slip

tire_combined_slip_RL:
  label: RL Com Slip

tire_combined_slip_RR:
  label: RR Com Slip

suspension_travel_meters_FL:
  label: FL Sus Trav
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

suspension_travel_meters_FR:
  label: FR Sus Trav
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

suspension_travel_meters_RL:
  label: RL Sus Trav
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

suspension_travel_meters_RR:
  label: RR Sus Trav
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

car_ordinal:
  label: Ordinal

car_class:
  label: Class

car_performance_index:
  label: PI

drivetrain_type:
  label: Drivetrain

num_cylinders:
  label: Cylinders

position_x:
  label: X Pos
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

position_y:
  label: Y Pos
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

position_z:
  label: Z Pos
  units:
    default: m
    imperial: ft
  factor:
    imperial: 3.28

speed:
  label: Speed
  units:
    default: mps
    imperial: mph
    metric: kph
  factor:
    imperial: 2.24
    metric: 3.6

power:
  label: Power
  units:
    default: w
    imperial: hp
    metric: hp
  factor:
    imperial: 0.001341022
    metric: 0.001341022

torque:
  label: Torque
  units:
    default: nm
    imperial: lb-ft
  factor:
    imperial: 0.73756

tire_temp_FL:
  label: FL Temp
  units:
    default: F
    metric: C
  factor:
    metric: 0.5556

tire_temp_FR:
  label: FR Temp
  units:
    default: F
    metric: C
  factor:
    metric: 0.5556

tire_temp_RL:
  label: RL Temp
  units:
    default: F
    metric: C
  factor:
    metric: 0.5556

tire_temp_RR:
  label: RR Temp
  units:
    default: F
    metric: C
  factor:
    metric: 0.5556

boost:
  label: Boost
  units:
    default: psi
    metric: bar
  factor:
    mertic: 0.0689476

# Fuel is sent as a value between 0 and 1, not actual amount left
fuel:
  label: Fuel

dist_traveled:
  label: Distance
  units:
    default: m
    imperial: mi
    metric: km
  factor:
    imperial: 0.0006213712
    metric: 0.001

best_lap_time:
  label: Best Lap
  units:
    default: s

last_lap_time:
  label: Last Lap
  units:
    default: s

cur_lap_time:
  label: Cur Lap
  units:
    default: s

cur_race_time:
  label: Total Time
  units:
    default: s

lap_no:
  label: Lap

race_pos:
  label: Pos

accel:
  label: Accel

brake:
  label: Brake

clutch:
  label: Clutch

handbrake:
  label: Handbrake

gear:
  label: Gear

steer:
  label: Steer

norm_driving_line:
  label: Line

norm_ai_brake_diff:
  label: Br Diff

tire_wear_FL:
  label: FL Wear

tire_wear_FR:
  label: FR Wear

tire_wear_RL:
  label: RL Wear

tire_wear_RR:
  label: RR Wear

track_ordinal:
  label: Track